version: '3.8'

services:
  api-election-issues:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/election_issues
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - election_issues_network
    depends_on:
      - postgres
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload --workers 4

  postgres:
    image: postgres
    restart: always
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=election_issues
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - election_issues_network

networks:
  election_issues_network:
    driver: bridge
