"""empty message

Revision ID: 8f28a97ed93e
Revises: 4d8ef35ee6b4
Create Date: 2024-07-15 21:50:49.727027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f28a97ed93e'
down_revision: Union[str, None] = '4d8ef35ee6b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers_questions',
    sa.Column('answers_id', sa.UUID(), nullable=True),
    sa.Column('questions_answers_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['questions_answers_id'], ['questions_answers.id'], )
    )
    op.drop_constraint('answers_questions_answers_id_fkey', 'answers', type_='foreignkey')
    op.drop_column('answers', 'questions_answers_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('questions_answers_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('answers_questions_answers_id_fkey', 'answers', 'questions_answers', ['questions_answers_id'], ['id'])
    op.drop_table('answers_questions')
    # ### end Alembic commands ###
